name: builds

on:
  push:
    tags:
      - "v*.*.*"
      - "test-v*.*.*"

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Install Tauri CLI
        run: cargo install tauri-cli --locked

      - name: Build Tauri app
        run: npm run tauri build

      - name: Upload platform bundle
        uses: actions/upload-artifact@v4
        with:
          name: bundle-${{ matrix.platform }}
          path: |
            src-tauri/target/release/bundle/**

  release:
    name: Release artifacts
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release

      - name: List release contents (debug)
        run: ls -R ./release

      - name: Create GitHub Release and upload binaries
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ contains(github.ref_name, 'test-') && '⚠️ This is a test release.' || '✅ Stable production release.' }}
          files: |
            release/**/**/*.dmg
            release/**/**/*.msi
            release/**/**/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
